# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 13.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Open VPN
      run: sudo apt-get install openvpn
    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: 'https://bitbucket.brown.edu'
        TLS_KEY: ${{ secrets.TLS_KEY }}
      env:
        CA_CRT: ${{ secrets.CA_CRT}}
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm test
