# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 13.x]
        
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: critical_review
      DB_USERNAME: user
      DB_PASSWORD: pass

    steps:
    - uses: actions/checkout@v2
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: critical_review
        postgresql user: user
        postgresql password: pass
      
    - name: Install Open VPN
      run: sudo apt-get install openvpn
    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: 'perfmon.cs.brown.edu'
        FILE_OVPN: '.github/vpn/config.ovpn'
        SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
        TLS_KEY: ${{ secrets.TLS_KEY }}
      env:
        CA_CRT: ${{ secrets.CA_CRT}}
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm test
